<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MuseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuseeRepository extends EntityRepository
{
    /**
     * How many musees should be displayed on a single page.
     *
     * @var int
     */
    public static $PAGE_SIZE = 10;

    /**
     * Get all musees from a specific page.
     * @param int $page
     * @return array
     */
    public function getByPage($page)
    {
        return $this->createQueryBuilder('m')
            ->setFirstResult(($page - 1) * self::$PAGE_SIZE)
            ->setMaxResults(self::$PAGE_SIZE)
            ->getQuery()
            ->getArrayResult();
    }

    /**
     * @param int $page
     * @return array
     */
    public function getByPageOrderedByArondissement($page)
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.codePostal', 'ASC')
            ->setFirstResult(($page - 1) * self::$PAGE_SIZE)
            ->setMaxResults(self::$PAGE_SIZE)
            ->getQuery()
            ->getArrayResult();
    }

    /**
     * Get the total number of musees.
     * @return int
     */
    public function getTotalCount()
    {
        return $this->createQueryBuilder('m')
            ->select('count(m)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Get the number of pages that can be displayed.
     * @return int
     */
    public function getNrOfPages()
    {
        return ceil($this->getTotalCount() / self::$PAGE_SIZE);
    }
}
